# Configuration for the labeler action
# https://github.com/actions/labeler

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

# Glossary updates
glossary:
  - changed-files:
    - any-glob-to-any-file: 'glossary.md'

# Character directory updates
character-directory:
  - changed-files:
    - any-glob-to-any-file: 'character-directory.md'

# Table of contents updates
table-of-contents:
  - changed-files:
    - any-glob-to-any-file: 'table-of-contents.md'

# README updates
readme:
  - changed-files:
    - any-glob-to-any-file: 'README.md'

# GitHub configuration changes (excluding workflows)
github-config:
  - changed-files:
    - any-glob-to-any-file: ['.github/*.yml', '.github/*.md']

# Workflow changes
workflow:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'
